Fix numpy pinning
conda-forge/mdanalysis-feedstock pull request #40
Opened 2022-05-11 09:51 UTC by joaander

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes https://github.com/MDAnalysis/mdanalysis/issues/3660

Remove numpy > 1.18.0 specification. This causes conda-smithy to remove the numpy pinning from the build, resulting in a build against the latest numpy ABI. After this change, conda-smith rerenders the build with the proper pinning.

2022-05-11 09:51 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-05-11 09:53 UTC, IAlibay commented
Thanks for this PR, I'm not sure removing the 1.18.0 spec is the right way to go here, I'm planning to experiment on this further later today.

2022-05-11 10:12 UTC, joaander commented
> Thanks for this PR, I'm not sure removing the 1.18.0 spec is the right way to go here, I'm planning to experiment on this further later today.

Alright. The conda-forge gitter channel is a good resource for help sorting out pinning issues.

2022-05-11 17:25 UTC, IAlibay requested changes
Can we try this change suggested by @mikemhenry ? From discussions it probably will have the same behaviour as the defaults triggered here (so the current state of this solution is probably fine), but at least we can make sure we've been following whatever guidance has been bestowed to us by numpy / conda-forge.

2022-05-11 17:25 UTC, IAlibay commented on recipe/meta.yaml
> +    - numpy
```suggestion
    - {{ pin_compatible('numpy') }}
```

2022-05-11 18:14 UTC, joaander commented
@conda-forge-admin, please rerender

2022-05-11 21:19 UTC, IAlibay commented
@conda-forge-admin, please restart ci

2022-05-12 06:52 UTC, richardjgowers approved these changes

2022-05-12 12:35 UTC, IAlibay approved these changes
lgtm thanks @joaander !

2022-05-12 12:39 UTC, merged